  spring:
    application:
      name: db-service

    server:
      port: 8181

  eureka:
     instance:
       hostname: localhost
     client:
       register-with-eureka: true
       fetch-registry: true
       service-url:
        defaultZone: http://localhost:8080/eureka

